modLoader="javafml"
loaderVersion="[1,)"
license="OSL-3.0"
issueTrackerURL="${issue_url}"

[[mods]]
modId="nolijium_common"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="icon.png"
authors="${nolij}"
description="""
${mod_description}
"""

[[dependencies.nolijium_common]]
modId="minecraft"
mandatory=true
versionRange="*"
ordering="NONE"
side="CLIENT"