modLoader="javafml"
loaderVersion="[1,)"
license="OSL-3.0"
issueTrackerURL="${issue_url}"

[[mixins]]
config="nolijium-common.mixins.json"

[[mods]]
modId="nolijium_common"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="icon.png"
authors="${nolij}"
description="""
${mod_description}
"""